### ISSUE TITLE
Attention needed please 

### ISSUE THREAD

**Issue by wanbilliondollarss** [tls-attacker/TLS-Scanner#101]
If the target is vulnerable ,what will it indicate.As of now this is what im seeing  currently ,i dont if its vulnerable .
INFO : Main - Performing Scan, this may take some time...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO : ThreadedScanJobExecutor - Common bugs probe executed
INFO : ThreadedScanJobExecutor - Server name indication (SNI) probe executed
INFO : ThreadedScanJobExecutor - Compression probe executed
INFO : ThreadedScanJobExecutor - Protocol version probe executed
INFO : ThreadedScanJobExecutor - Cipher suite order probe executed
INFO : ThreadedScanJobExecutor - Client certificate authentication support probe executed
INFO : ThreadedScanJobExecutor - Signature Hash Algorithm Order probe executed
INFO : ThreadedScanJobExecutor - Record fragmentation probe executed
INFO : ThreadedScanJobExecutor - Early CCS probe executed
INFO : ThreadedScanJobExecutor - Tokenbinding probe executed
INFO : ThreadedScanJobExecutor - HTTP header probe executed
INFO : ThreadedScanJobExecutor - Cipher suite probe executed
INFO : ThreadedScanJobExecutor - Extensions probe executed
INFO : ThreadedScanJobExecutor - Signature and hash algorithm probe executed
INFO : ThreadedScanJobExecutor - TLS Fallback SCSV probe executed
INFO : ThreadedScanJobExecutor - Hello retry probe executed
INFO : ThreadedScanJobExecutor - ESNI probe executed
INFO : ThreadedScanJobExecutor - HTTP false start probe executed
WARN : X509Certificate - X.509 Certificate does not contain an EC PublicKey. Returning null.
INFO : ThreadedScanJobExecutor - Certificate probe executed
INFO : ThreadedScanJobExecutor - EC point formats probe executed
INFO : ThreadedScanJobExecutor - Resumption probe executed
INFO : ThreadedScanJobExecutor - Renegotiation probe executed
INFO : ThreadedScanJobExecutor - Padding oracle probe executed

**Comment by ic0ns** [comment]
The scan did not finish yet. If there is an issue it will say so.
