### ISSUE TITLE
PublicKey printout

### ISSUE THREAD

**Issue by J08nY** [tls-attacker/TLS-Scanner#68]
I ran `java -jar TLS-Server-Scanner.jar -connect neuromancer.sk:443` using the latest release (4.0.0).
When it printed out the  Certificate Chain it printed the following as the `PublicKey` entry:

```
 PublicKey			 : de.rub.nds.tlsattacker.core.crypto.keys.CustomRsaPublicKey@26cc7912
```

So I guess a `toString` or some other serialization method implementation is missing to display the pubkey.

**Comment by ic0ns** [comment]
Oops. I will fix it in the next release

**Comment by ic0ns** [comment]
The key should now get printed
