### ISSUE TITLE
illegal reflective access deprecated

### ISSUE THREAD

**Issue by roycewilliams** [tls-attacker/TLS-Scanner#71]
Just in case this wasn't already known.
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by de.rub.nds.tlsattacker.core.crypto.PseudoRandomFunction (file:[redacted]/TLS-Scanner/apps/lib/TLS-Core-3.7.0.jar) to field javax.crypto.spec.SecretKeySpec.key
WARNING: Please consider reporting this to the maintainers of de.rub.nds.tlsattacker.core.crypto.PseudoRandomFunction
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by ugu5ma** [comment]
Got the same warning on my end.
The scan finishes successful  even with this warning.

BTW: Thanks for your hard work, I am very impressed :)

**Comment by ic0ns** [comment]
Thanks for issue! Which java version are you using? 11? TLS-Attacker usually runs on Java 8 but we are currently trying to move towards newer version so maybe this is where this is coming from.

**Comment by roycewilliams** [comment]
Ah, indeed - yep, this is Java 11.

**Comment by ic0ns** [comment]
@Aldurim this probably has to be fixed in TLS-Attacker core - can you take a look whats causing this?

**Comment by Aldurim** [comment]
Hi, I am trying to reproduce these warnings.
Can you tell me, what you did to trigger them?

**Comment by ic0ns** [comment]
I think if you use Java 11 and start the TLS-Scanner you should see this directly.

**Comment by Aldurim** [comment]
Ah yes, I got it, thank you.
