### ISSUE TITLE
Custom CA

### ISSUE THREAD

**Issue by bennysp** [tls-attacker/TLS-Scanner#72]
Hi,

Is there a way to pass a custom CA bundle to validate the cert?

Thanks

**Comment by ic0ns** [comment]
There is no command line flag for that as of now. We currently validate the trust against the CA's from here: https://github.com/nabla-c0d3/trust_stores_observatory 
What you can do is add your CA's to one of the yaml files for the different browsers and add the certificate to the certificate folder. We can add a flag for additional custom ca's in the next release

**Comment by bennysp** [comment]
Thanks @ic0ns!
