### ISSUE TITLE
Missing mapping in output between Guidelines and Recommondations

### ISSUE THREAD

**Issue by craig** [tls-attacker/TLS-Scanner#84]
The program has the following output: 

```
--|Guideline BSI TR-02102-2
Passed: 24
Skipped: 0
Failed: 1
Uncertain: 0
```

However, it does not list which recommondations are given due to which guideline.

**Comment by ic0ns** [comment]
Our recommendations are not coming from the technical guidelines. We (@jurajsomorovsky and I) designed them based on our own experience and risk assessment. The Guideline details are currently committed in the default detailed scan (as the report is already long enough as it is), but you can print them by running with the `-reportDetail ALL` flag
