### ISSUE TITLE
ALPACA StrictSNI test issue

### ISSUE THREAD

**Issue by gj1803** [tls-attacker/TLS-Scanner#95]
When testing the ALPACA probe I see that the SNI name is set to "notarealtls-attackerhost.com" in the isSupportingStrictSni method, however on my server trace the SNI value is still set to the default (localhost). This causes the SNI mitigation test to fail for the server even though I have implemented strict SNI logic, it seems he SNI value is not being set correctly in the TLSScanner client.

**Comment by NErinola** [comment]
Fixed with the release of v6.1.0.
