### ISSUE TITLE
unable to initialize main class de.ruub.nds.tlsattacker.server.Main

### ISSUE THREAD

**Issue by Trickevtarike** [tls-attacker/TLS-Scanner#98]
can someone please tell what is wrong? Thanks
![Bild_2024-10-15_125436920](https://github.com/user-attachments/assets/ce633fc0-e8eb-4a78-96ec-f0955e143671)

**Comment by ic0ns** [comment]
this is the wrong repo for this issue - the issue is in TLS-Attacker and not in TLS-Scanner. Anyways, your issue is that you are starting the jar from the target folder and not from the apps/ folder. The jar in the target/ folder does not bundle dependencies which are missing here.

**Comment by Trickevtarike** [comment]
oh yes. Thanks for the help.
