### ISSUE TITLE
the variables for prf are being checked incorrectly

### ISSUE THREAD

**Issue by hachuping123** [tls-attacker/TLS-Scanner#99]
It appears that the variables SUPPORTS_SHA256_PRF and SUPPORTS_SHA384_PRF are being checked incorrectly.

In CipherSuiteEvaluationHelper.java, the mergeData() method checks the following:

if (prfAlgorithm == PRFAlgorithm.TLS_PRF_LEGACY) {
    supportsLegacyPrf = TestResults.TRUE;
}
if (prfAlgorithm == PRFAlgorithm.TLS_PRF_LEGACY) {
    supportsSha256Prf = TestResults.TRUE;
}
if (prfAlgorithm == PRFAlgorithm.TLS_PRF_LEGACY) {
    supportsSha384Prf = TestResults.TRUE;
}

**Comment by ic0ns** [comment]
Good catch!

**Comment by ic0ns** [comment]
Fixed in v6.1.1
